/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: qpsmessage.proto */

#ifndef PROTOBUF_C_qpsmessage_2eproto__INCLUDED
#define PROTOBUF_C_qpsmessage_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1000000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _QpsMessage QpsMessage;


/* --- enums --- */


/* --- messages --- */

struct  _QpsMessage
{
  ProtobufCMessage base;
  protobuf_c_boolean has_id;
  int32_t id;
  float qps;
  char *result;
  char *view;
  char *zone;
  protobuf_c_boolean has_time;
  uint32_t time;
};
#define QPS_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&qps_message__descriptor) \
    , 0,0, 0, NULL, NULL, NULL, 0,0 }


/* QpsMessage methods */
void   qps_message__init
                     (QpsMessage         *message);
size_t qps_message__get_packed_size
                     (const QpsMessage   *message);
size_t qps_message__pack
                     (const QpsMessage   *message,
                      uint8_t             *out);
size_t qps_message__pack_to_buffer
                     (const QpsMessage   *message,
                      ProtobufCBuffer     *buffer);
QpsMessage *
       qps_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   qps_message__free_unpacked
                     (QpsMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*QpsMessage_Closure)
                 (const QpsMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor qps_message__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_qpsmessage_2eproto__INCLUDED */
