# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qpsmessage.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='qpsmessage.proto',
  package='',
  serialized_pb='\n\x10qpsmessage.proto\"_\n\nQpsMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0b\n\x03qps\x18\x02 \x02(\x02\x12\x0e\n\x06result\x18\x03 \x01(\t\x12\x0c\n\x04view\x18\x04 \x01(\t\x12\x0c\n\x04zone\x18\x05 \x01(\t\x12\x0c\n\x04time\x18\x06 \x01(\x07')




_QPSMESSAGE = _descriptor.Descriptor(
  name='QpsMessage',
  full_name='QpsMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='QpsMessage.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='qps', full_name='QpsMessage.qps', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='result', full_name='QpsMessage.result', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='view', full_name='QpsMessage.view', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='zone', full_name='QpsMessage.zone', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='QpsMessage.time', index=5,
      number=6, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=20,
  serialized_end=115,
)

DESCRIPTOR.message_types_by_name['QpsMessage'] = _QPSMESSAGE

class QpsMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _QPSMESSAGE

  # @@protoc_insertion_point(class_scope:QpsMessage)


# @@protoc_insertion_point(module_scope)
