/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: qpsmessage.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "qpsmessage.pb-c.h"
void   qps_message__init
                     (QpsMessage         *message)
{
  static QpsMessage init_value = QPS_MESSAGE__INIT;
  *message = init_value;
}
size_t qps_message__get_packed_size
                     (const QpsMessage *message)
{
  assert(message->base.descriptor == &qps_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t qps_message__pack
                     (const QpsMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &qps_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t qps_message__pack_to_buffer
                     (const QpsMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &qps_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
QpsMessage *
       qps_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (QpsMessage *)
     protobuf_c_message_unpack (&qps_message__descriptor,
                                allocator, len, data);
}
void   qps_message__free_unpacked
                     (QpsMessage *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &qps_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor qps_message__field_descriptors[6] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(QpsMessage, has_id),
    offsetof(QpsMessage, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "qps",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(QpsMessage, qps),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "result",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(QpsMessage, result),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "view",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(QpsMessage, view),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "zone",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(QpsMessage, zone),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(QpsMessage, has_time),
    offsetof(QpsMessage, time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned qps_message__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = qps */
  2,   /* field[2] = result */
  5,   /* field[5] = time */
  3,   /* field[3] = view */
  4,   /* field[4] = zone */
};
static const ProtobufCIntRange qps_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor qps_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "QpsMessage",
  "QpsMessage",
  "QpsMessage",
  "",
  sizeof(QpsMessage),
  6,
  qps_message__field_descriptors,
  qps_message__field_indices_by_name,
  1,  qps_message__number_ranges,
  (ProtobufCMessageInit) qps_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
